name: "Github Feed"

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

env:
  PROJECT_NAME: 'WMJ.ScaleModelLibrary'
  PROJECT_PATH: 'WMJ.ScaleModelLibrary/WMJ.ScaleModelLibrary.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/${{ secrets.USERNAME }}/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
    - name: Get version from tag
      id: getversion
      uses: wayne-mj/getversion@v1.3

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.getversion.outputs.release_version }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package to Github feed'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate